### ISSUE TITLE
Hyperbridge Support

### ISSUE THREAD

**Issue by Wizdave97** [mimir-labs/mimir-wallet#83]
Hello team, we'd like for the Mimir multi-sig wallet to add support for Hyperbridge(Nexus).
Hyperbridge uses Keccak256 hashing for its runtime.

Hyperbridge can be supported in polkadotjs by adding the following when creating the ApiPromise 

```javascript
typesBundle: {
      spec: {
        nexus: {
          hasher: keccakAsU8a,
        },
      },
    },
```

**Comment by gravitiny** [comment]
Hi,
Glad to hear from Hyperbridge^^
We will start the integration. We hope get further connection. My TG handle is @gravitinyliu

**Comment by Wizdave97** [comment]
Appreciate it.
